"""
Unit tests for HTML newsletter template rendering.

Tests render with mock data, verifying structure and compliance.
Spec refs: Section 11.1, FR-022, FR-023, FR-024, FR-025.
"""

import pytest

from newsletter_agent.tools.formatter import render_newsletter


def _make_mock_data(topic_count=3):
    """Build mock template data for rendering."""
    sections = []
    all_sources = []
    summary = []
    for i in range(topic_count):
        name = f"Topic {i}"
        src = {"url": f"https://example.com/{i}", "title": f"Source {i}"}
        sections.append({
            "title": name,
            "body_html": f"<p>Analysis of {name} with <a href=\"https://example.com/{i}\">Source {i}</a>.</p>",
            "sources": [src],
        })
        all_sources.append(src)
        summary.append({"topic": name, "summary": f"Overview of {name}."})

    return {
        "newsletter_title": "Weekly Tech Digest",
        "newsletter_date": "2026-03-14",
        "executive_summary": summary,
        "sections": sections,
        "all_sources": all_sources,
        "generation_time_seconds": 120.5,
    }


class TestTemplateRendering:
    def test_renders_without_error(self):
        html = render_newsletter(_make_mock_data())
        assert html
        assert "<!DOCTYPE html>" in html

    def test_title_present(self):
        html = render_newsletter(_make_mock_data())
        assert "Weekly Tech Digest" in html

    def test_date_present(self):
        html = render_newsletter(_make_mock_data())
        assert "2026-03-14" in html

    def test_executive_summary_section(self):
        html = render_newsletter(_make_mock_data())
        assert "Executive Summary" in html
        assert "Topic 0" in html
        assert "Overview of Topic 0." in html

    def test_executive_summary_bulleted(self):
        html = render_newsletter(_make_mock_data())
        # Verify list structure
        assert "<ul" in html
        assert "<li" in html


class TestSectionOrder:
    def test_header_before_summary(self):
        html = render_newsletter(_make_mock_data())
        header_pos = html.find("Weekly Tech Digest")
        summary_pos = html.find("Executive Summary")
        assert header_pos < summary_pos

    def test_summary_before_toc(self):
        html = render_newsletter(_make_mock_data())
        summary_pos = html.find("Executive Summary")
        toc_pos = html.find("In This Issue")
        assert summary_pos < toc_pos

    def test_toc_before_sections(self):
        html = render_newsletter(_make_mock_data())
        toc_pos = html.find("In This Issue")
        section_pos = html.find('id="section-0"')
        assert toc_pos < section_pos

    def test_sections_before_appendix(self):
        html = render_newsletter(_make_mock_data())
        section_pos = html.find('id="section-0"')
        appendix_pos = html.find("All Sources")
        assert section_pos < appendix_pos

    def test_appendix_before_footer(self):
        html = render_newsletter(_make_mock_data())
        appendix_pos = html.find("All Sources")
        footer_pos = html.find("Generated by Newsletter Agent")
        assert appendix_pos < footer_pos


class TestTOC:
    def test_toc_has_anchor_links(self):
        html = render_newsletter(_make_mock_data())
        assert 'href="#section-0"' in html
        assert 'href="#section-1"' in html
        assert 'href="#section-2"' in html

    def test_toc_entries_match_sections(self):
        html = render_newsletter(_make_mock_data())
        for i in range(3):
            assert f'href="#section-{i}"' in html
            assert f'id="section-{i}"' in html


class TestInlineCSS:
    def test_no_link_tags(self):
        html = render_newsletter(_make_mock_data())
        assert "<link" not in html

    def test_no_external_style(self):
        html = render_newsletter(_make_mock_data())
        assert "<style" not in html

    def test_max_width_600px(self):
        html = render_newsletter(_make_mock_data())
        assert "max-width: 600px" in html

    def test_inline_styles_present(self):
        html = render_newsletter(_make_mock_data())
        assert 'style="' in html


class TestTopicVariants:
    def test_single_topic(self):
        html = render_newsletter(_make_mock_data(topic_count=1))
        assert "Topic 0" in html
        assert 'id="section-0"' in html

    def test_five_topics(self):
        html = render_newsletter(_make_mock_data(topic_count=5))
        for i in range(5):
            assert f"Topic {i}" in html
            assert f'id="section-{i}"' in html

    def test_empty_sources_hides_appendix(self):
        data = _make_mock_data(topic_count=1)
        data["all_sources"] = []
        html = render_newsletter(data)
        # Source appendix section should not appear
        assert "All Sources" not in html


class TestFooter:
    def test_footer_has_date(self):
        html = render_newsletter(_make_mock_data())
        footer_pos = html.find("Generated by Newsletter Agent")
        assert footer_pos > 0
        # Date should be in footer area
        assert "2026-03-14" in html[footer_pos:]

    def test_footer_has_timing(self):
        html = render_newsletter(_make_mock_data())
        assert "120.5s" in html


class TestEdgeCases:
    def test_empty_executive_summary(self):
        data = _make_mock_data()
        data["executive_summary"] = []
        html = render_newsletter(data)
        assert "No executive summary available" in html

    def test_html_special_chars_in_title(self):
        data = _make_mock_data()
        data["newsletter_title"] = "AI & Machine Learning <Report>"
        html = render_newsletter(data)
        assert "&amp;" in html
        assert "&lt;" in html
